application: murphylog
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/\.git/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$

handlers:

- url: /static
  static_dir: static

- url: /feed
  script: feed.py

- url: .*
  script: main.py
