application: murphytalk-log
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/\.git/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- bulk\.py
- .*\.sh
- prepare_csv.py
- .*\.csv

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /blogimages
  static_dir: blogimages

- url: .*
  script: main.py
